{% set version = "0.4.0" %}
{% set name = "rhapsody" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 159cad70b5c34e9b36f24f8975933de06e541240151bd977be8c79ee609045b8


build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

  entry_points:
    - qiime2.plugins = rhapsody.q2.plugin_setup:plugin

requirements:
  host:
    - python >=3
    - pip

  run:

    - python >=3
    - ipython
    - pandas
    - click
    - tensorflow >1.7
    - scikit-bio >0.5.4
    - scikit-learn
    - tqdm
    - h5py
    - biom-format

test:
  imports:
    - rhapsody

about:
  home: https://github.com/biocore/rhapsody
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Neural networks for microbe-metabolite interaction analysis'

extra:
  recipe-maintainers:
    - mortonjt
