travis:
  secure:
    BINSTAR_TOKEN: EjNWWnbXxWc9Iqo8uGeAlugn8BZkB3Eo4KEJJk9Gy/DO/4Jb9F0wrfVeP0Rx9uGFIRgCkDhQC16SNMKhCG6A3/6DOxKx+XTwONWDgvICRVEAfsgiKwc/+zoBJ3xHDt8+XLJaEJzMjucdbdLRPYpFpq51V88Vhs7vPVQkRfkv3FP40wMkXE+ordFbrd+rh9w1jcCdY+g4VkQTLZBt2dfO3U3Sxa/rlVVbp/hlfGYVM94pN+EHye800u7qHVXNV9V/uavS+7AIyq67nRiXjw59DVxuHc91BxJb+H7msXq9JRFaziTZA/HQfUC0haszBReYHZ/6UL1I3uaHqQaDquC6RlCy9L67f24UAKdBqTxgkE8YEEYIlQOMNxiYo09w70a/97s9qeAuBUEiiquZqedpa91Tpv7PnWnR+ypxFIPKQ0FLsUmgdQZNanu+7jDjNCqHgIWrgCvDkSbMZNVC04x8e+djEkUFFs67tDyf4BCb52sn5l8nT9Yy6FI+WY0Vi+lFPedWZ9jzMOJCZE0lcqI/YI9yPuub8Fp9IocWrDxLmcCCJRSEOzi0GgnhW5/0DUKLyC8Vc1Dg8rL9ZelEzb4UvYmKZi1hJydw/CSNaOZJsVdPfdxWG3mmM2p+3THFq67UFe4dlKOnakHxqbAM93KrWmr4iU/7PandiUu0sEPK4A4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
